# ~/.config/starship.toml
format = '''
$os  in $directory
$character'''
add_newline = true
command_timeout = 1000
# format = """$os$hostname$directory"""
# move the rest of the prompt to the right
right_format = """$git_metrics$git_branch$git_status$python"""

# Drop ugly default prompt characters
[character]
success_symbol = "[ ](green bold)"
error_symbol = "[ ](red bold)"
vicmd_symbol = "[ ](blue bold)"
# ---

# Display OS symbol at the very begining
[os]
format = '[$symbol](bold grey)'   
disabled = false

# ---y

# Shows the username
[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = false

# Shows the hostname
[hostname]
ssh_only = false
ssh_symbol = " "
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current directory
[directory]
style = 'bold purple'
truncation_length = 10
truncation_symbol = '…/  '
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = '[$path]($style)[$read_only]($read_only_style) '
disabled = false

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = ' 🏳'
up_to_date = ''
untracked = '  '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '  '
modified = '  '
staged = '[++\($count\)](green)'
renamed = ' 襁'
deleted = '  '
disabled = false

# Shows current git branch
[git_branch]
symbol = '󰊤   = '
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold yellow'
disabled = false

#Show git metrics i.e: puts, files, pulls, etc.
[git_metrics]
disabled = false

[python]
symbol = '  '
style = 'yellow bold'
virtualenv = 'venv'
version = 'v${raw}'
format = 'via [${symbol}(${version} )(\($virtualenv\) )]($style)'

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "


[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

# [fossil_branch]
# symbol = " "
#
# [git_branch]
# symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "


[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = "" 
# " " " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

# [python]
# symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
