# yazi.toml
[manager]
sort_by = "alphabetical"
sort_sensitive = true
linemode = "mtime"
show_hidden = true
show_symlink = true

[preview]
tab_size = 1
max_width = 1500
max_height = 3000
cache_dir = ""
image_filter = "triangle"
image_quality = 75
