# yazi.toml
[manager]
sort_by = "alphabetical"
sort_sensitive = true
linemode = "mtime"
show_hidden = false
show_symlink = true

[preview]
tab_size = 1
max_width = 1500
max_height = 3000
cache_dir = ""
image_filter = "triangle"
image_quality = 75

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
# ...
